DROP TABLE IF EXISTS music CASCADE;

CREATE TABLE music (
	id INT AUTO_INCREMENT,
	song_name VARCHAR(255) NOT NULL,
	artist VARCHAR(255) NOT NULL,
	release_year VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);